/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'orderId' : IDL.Nat,
  'deliveryPlace' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
});
export const MenuItem = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({ 'itemName' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'orderId' : IDL.Nat,
    'deliveryPlace' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
  });
  const MenuItem = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };